version: "3.9"
services:
    api:
        image: alertapi.azurecr.io/alertapi:latest
        build: ./API/
        ports:
            - "8000:8000"

    ui:
        image: alertui.azurecr.io/alertui:latest
        build: ./WebApp2.0/
        ports:
            - "8080:4200"
        volumes:
            - ./WebApp2.0/src:/webapp/src